In [1]:
# Import the necessary packages.
import pandas as pd

In [2]:
import json

In [91]:
import numpy as np

In [3]:
from pandas.io.json import json_normalize

## Question 1
Find the 10 countries with the most projects.

In [4]:
# Set worldbank as the dataframe populated from json file.
worldbank = pd.read_json('world_bank_projects.json')

In [5]:
# Have a look at the layout.
worldbank.head()

,_id,approvalfy,board_approval_month,boardapprovaldate,borrower,closingdate,country_namecode,countrycode,countryname,countryshortname,...,sectorcode,source,status,supplementprojectflg,theme1,theme_namecode,themecode,totalamt,totalcommamt,url
0,{'$oid': '52b213b38594d8a2be17c780'},1999,November,2013-11-12T00:00:00Z,FEDERAL DEMOCRATIC REPUBLIC OF ETHIOPIA,2018-07-07T00:00:00Z,Federal Democratic Republic of Ethiopia!$!ET,ET,Federal Democratic Republic of Ethiopia,Ethiopia,...,"ET,BS,ES,EP",IBRD,Active,N,"{'Percent': 100, 'Name': 'Education for all'}","[{'code': '65', 'name': 'Education for all'}]",65,130000000,130000000,http://www.worldbank.org/projects/P129828/ethi...
1,{'$oid': '52b213b38594d8a2be17c781'},2015,November,2013-11-04T00:00:00Z,GOVERNMENT OF TUNISIA,NaN,Republic of Tunisia!$!TN,TN,Republic of Tunisia,Tunisia,...,"BZ,BS",IBRD,Active,N,"{'Percent': 30, 'Name': 'Other economic manage...","[{'code': '24', 'name': 'Other economic manage...","54,24",0,4700000,http://www.worldbank.org/projects/P144674?lang=en
2,{'$oid': '52b213b38594d8a2be17c782'},2014,November,2013-11-01T00:00:00Z,MINISTRY OF FINANCE AND ECONOMIC DEVEL,NaN,Tuvalu!$!TV,TV,Tuvalu,Tuvalu,...,TI,IBRD,Active,Y,"{'Percent': 46, 'Name': 'Regional integration'}","[{'code': '47', 'name': 'Regional integration'...","52,81,25,47",6060000,6060000,http://www.worldbank.org/projects/P145310?lang=en
3,{'$oid': '52b213b38594d8a2be17c783'},2014,October,2013-10-31T00:00:00Z,MIN. OF PLANNING AND INT'L COOPERATION,NaN,Republic of Yemen!$!RY,RY,Republic of Yemen,"Yemen, Republic of",...,JB,IBRD,Active,N,"{'Percent': 50, 'Name': 'Participation and civ...","[{'code': '57', 'name': 'Participation and civ...","59,57",0,1500000,http://www.worldbank.org/projects/P144665?lang=en
4,{'$oid': '52b213b38594d8a2be17c784'},2014,October,2013-10-31T00:00:00Z,MINISTRY OF FINANCE,2019-04-30T00:00:00Z,Kingdom of Lesotho!$!LS,LS,Kingdom of Lesotho,Lesotho,...,"FH,YW,YZ",IBRD,Active,N,"{'Percent': 30, 'Name': 'Export development an...","[{'code': '45', 'name': 'Export development an...","41,45",13100000,13100000,http://www.worldbank.org/projects/P144933/seco...

In [7]:
# Have a look at the column names available.
worldbank.columns

Index(['_id', 'approvalfy', 'board_approval_month', 'boardapprovaldate',
       'borrower', 'closingdate', 'country_namecode', 'countrycode',
       'countryname', 'countryshortname', 'docty', 'envassesmentcategorycode',
       'grantamt', 'ibrdcommamt', 'id', 'idacommamt', 'impagency',
       'lendinginstr', 'lendinginstrtype', 'lendprojectcost',
       'majorsector_percent', 'mjsector_namecode', 'mjtheme',
       'mjtheme_namecode', 'mjthemecode', 'prodline', 'prodlinetext',
       'productlinetype', 'project_abstract', 'project_name', 'projectdocs',
       'projectfinancialtype', 'projectstatusdisplay', 'regionname', 'sector',
       'sector1', 'sector2', 'sector3', 'sector4', 'sector_namecode',
       'sectorcode', 'source', 'status', 'supplementprojectflg', 'theme1',
       'theme_namecode', 'themecode', 'totalamt', 'totalcommamt', 'url'],
      dtype='object')

In [32]:
# The number of entries should equal the naumber of projects.
# So, count the number of time each country occurs.
worldbank['countryshortname'].value_counts()

Indonesia                           19
China                               19
Vietnam                             17
India                               16
Yemen, Republic of                  13
Nepal                               12
Morocco                             12
Bangladesh                          12
Africa                              11
Mozambique                          11
Pakistan                             9
Brazil                               9
Burkina Faso                         9
Tajikistan                           8
Tanzania                             8
Armenia                              8
Jordan                               7
Nigeria                              7
Lao People's Democratic Republic     7
Kyrgyz Republic                      7
Peru                                 6
Afghanistan                          6
Nicaragua                            6
Kenya                                6
Congo, Democratic Republic of        6
West Bank and Gaza                   6
Moldova                              5
Niger                                5
Honduras                             5
Papua New Guinea                     5
                                    ..
Bolivia                              2
Mongolia                             2
Seychelles                           2
Mauritius                            2
Argentina                            2
Egypt, Arab Republic of              2
Guatemala                            2
Kiribati                             1
Romania                              1
Europe and Central Asia              1
Poland                               1
Thailand                             1
Costa Rica                           1
Chile                                1
Angola                               1
Serbia                               1
Sri Lanka                            1
Bosnia and Herzegovina               1
Tonga                                1
Central African Republic             1
Panama                               1
Antigua and Barbuda                  1
Zimbabwe                             1
Namibia                              1
Congo, Republic of                   1
Belarus                              1
Chad                                 1
Cape Verde                           1
East Asia and Pacific                1
Tuvalu                               1
Name: countryshortname, Length: 118, dtype: int64

In [80]:
# to be sure Country count really does = occurence,
# chain methods to sort by project id.
worldbank.groupby('countryshortname').count().sort_values('_id', ascending=False)

,_id,approvalfy,board_approval_month,boardapprovaldate,borrower,closingdate,country_namecode,countrycode,countryname,docty,...,source,status,supplementprojectflg,theme1,theme_namecode,themecode,totalamt,totalcommamt,url,Top10projectscount
countryshortname,,,,,,,,,,,,,,,,,,,,,
China,19,19,19,19,19,16,19,19,19,19,...,19,19,19,19,17,17,19,19,19,0
Indonesia,19,19,19,19,19,15,19,19,19,14,...,19,19,19,19,19,19,19,19,19,0
Vietnam,17,17,17,17,17,14,17,17,17,16,...,17,17,16,17,17,17,17,17,17,0
India,16,16,16,16,15,13,16,16,16,16,...,16,16,16,16,16,16,16,16,16,0
"Yemen, Republic of",13,13,13,13,13,8,13,13,13,11,...,13,13,13,13,13,13,13,13,13,0
Nepal,12,12,12,12,11,7,12,12,12,12,...,12,12,12,12,11,11,12,12,12,0
Bangladesh,12,12,12,12,12,10,12,12,12,12,...,12,12,12,12,12,12,12,12,12,0
Morocco,12,12,12,12,12,11,12,12,12,10,...,12,12,12,12,11,11,12,12,12,0
Mozambique,11,11,11,11,11,9,11,11,11,10,...,11,11,11,11,11,11,11,11,11,0
Africa,11,11,11,11,11,7,11,11,11,10,...,11,11,11,11,11,11,11,11,11,0
Pakistan,9,9,9,9,9,7,9,9,9,9,...,9,9,9,9,9,9,9,9,9,0
Brazil,9,9,9,9,9,8,9,9,9,9,...,9,9,9,9,9,9,9,9,9,0
Burkina Faso,9,9,9,9,9,8,9,9,9,7,...,9,9,9,9,9,9,9,9,9,0
Armenia,8,8,8,8,8,6,8,8,8,5,...,8,8,8,8,8,8,8,8,8,0
Tanzania,8,8,8,8,8,4,8,8,8,8,...,8,8,8,8,8,8,8,8,8,0
Tajikistan,8,8,8,8,8,6,8,8,8,7,...,8,8,8,8,8,8,8,8,8,0
Jordan,7,7,7,7,7,5,7,7,7,5,...,7,7,7,7,7,7,7,7,7,0
Nigeria,7,7,7,7,7,6,7,7,7,6,...,7,7,7,7,7,7,7,7,7,0
Lao People's Democratic Republic,7,7,7,7,6,6,7,7,7,7,...,7,7,7,7,7,7,7,7,7,0
Kyrgyz Republic,7,7,7,7,7,3,7,7,7,6,...,7,7,7,7,7,7,7,7,7,0
Kenya,6,6,6,6,6,5,6,6,6,6,...,6,6,6,6,6,6,6,6,6,0
"Congo, Democratic Republic of",6,6,6,6,6,4,6,6,6,5,...,6,6,6,6,6,6,6,6,6,0
Peru,6,6,6,6,5,5,6,6,6,5,...,6,6,6,6,6,6,6,6,6,0
Nicaragua,6,6,6,6,6,4,6,6,6,5,...,6,6,6,6,6,6,6,6,6,0
Afghanistan,6,6,6,6,6,5,6,6,6,6,...,6,6,6,6,6,6,6,6,6,0
West Bank and Gaza,6,6,6,6,6,4,6,6,6,6,...,6,6,6,6,6,6,6,6,6,0
Honduras,5,5,5,5,4,2,5,5,5,5,...,5,5,5,5,5,5,5,5,5,0
Haiti,5,5,5,5,5,4,5,5,5,5,...,5,5,5,5,5,5,5,5,5,0
Niger,5,5,5,5,5,4,5,5,5,5,...,5,5,5,5,5,5,5,5,5,0
Liberia,5,5,5,5,5,4,5,5,5,4,...,5,5,5,5,5,5,5,5,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Marshall Islands,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,0
"Egypt, Arab Republic of",2,2,2,2,2,2,2,2,2,1,...,2,2,2,2,2,2,2,2,2,0
Mauritania,2,2,2,2,2,2,2,2,2,1,...,2,2,2,2,1,1,2,2,2,0
Mauritius,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,0
Mexico,2,2,2,2,2,1,2,2,2,2,...,2,2,2,2,2,2,2,2,2,0
Mongolia,2,2,2,2,2,1,2,2,2,2,...,2,2,2,2,2,2,2,2,2,0
Ecuador,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,0
Cape Verde,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,0
Central African Republic,1,1,1,1,1,0,1,1,1,0,...,1,1,1,1,1,1,1,1,1,0
Panama,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,0
Bosnia and Herzegovina,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,0
Chad,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,0
Belarus,1,1,1,1,1,0,1,1,1,1,...,1,1,1,1,1,1,1,1,1,0
Antigua and Barbuda,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,0
Angola,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,0
Tuvalu,1,1,1,1,1,0,1,1,1,1,...,1,1,1,1,1,1,1,1,1,0
East Asia and Pacific,1,1,1,1,1,0,1,1,1,1,...,1,1,1,1,1,1,1,1,1,0
Chile,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,0
Tonga,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,0
"Congo, Republic of",1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,0
Costa Rica,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,0
Thailand,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,0
Namibia,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,0
Sri Lanka,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,0
Europe and Central Asia,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,0
Kiribati,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,0
Serbia,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,0
Romania,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,0
Poland,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,0
Zimbabwe,1,1,1,1,1,0,1,1,1,1,...,1,1,1,1,1,1,1,1,1,0

In [84]:
# investigate rows with Africa as country.
Africa=worldbank.loc[worldbank['countryshortname']=='Africa']
Africa

,_id,approvalfy,board_approval_month,boardapprovaldate,borrower,closingdate,country_namecode,countrycode,countryname,countryshortname,...,source,status,supplementprojectflg,theme1,theme_namecode,themecode,totalamt,totalcommamt,url,Top10projectscount
45,{'$oid': '52b213b38594d8a2be17c7ad'},2014,September,2013-09-12T00:00:00Z,ECOWAS,NaN,Africa!$!3A,3A,Africa,Africa,...,IBRD,Active,N,"{'Percent': 100, 'Name': 'Health system perfor...","[{'code': '67', 'name': 'Health system perform...",67,0,10000000,http://www.worldbank.org/projects/P125018/west...,NaN
46,{'$oid': '52b213b38594d8a2be17c7ae'},2014,September,2013-09-10T00:00:00Z,UGANDA-COMOROS,2018-06-30T00:00:00Z,Africa!$!3A,3A,Africa,Africa,...,IBRD,Active,N,"{'Percent': 20, 'Name': 'Administrative and ci...","[{'code': '25', 'name': 'Administrative and ci...","39,40,78,25",22000000,22000000,http://www.worldbank.org/projects/P118213/rcip...,NaN
51,{'$oid': '52b213b38594d8a2be17c7b3'},2014,September,2013-09-04T00:00:00Z,"OSS, IUCN, CILSS",NaN,Africa!$!3A,3A,Africa,Africa,...,IBRD,Active,N,"{'Percent': 20, 'Name': 'Biodiversity'}","[{'code': '80', 'name': 'Biodiversity'}, {'cod...","85,82,81,83,80",0,4630000,http://www.worldbank.org/projects/P130888/buil...,NaN
58,{'$oid': '52b213b38594d8a2be17c7ba'},2014,August,2013-08-28T00:00:00Z,BANK EXECUTED,NaN,Africa!$!3A,3A,Africa,Africa,...,IBRD,Active,N,"{'Percent': 50, 'Name': 'Biodiversity'}","[{'code': '80', 'name': 'Biodiversity'}, {'cod...","82,80",0,2000000,http://www.worldbank.org/projects/P144902?lang=en,NaN
65,{'$oid': '52b213b38594d8a2be17c7c1'},2014,August,2013-08-06T00:00:00Z,"BURUNDI,RWANDA,TANZANIA",2020-12-31T00:00:00Z,Africa!$!3A,3A,Africa,Africa,...,IBRD,Active,N,"{'Percent': 15, 'Name': 'Infrastructure servic...","[{'code': '39', 'name': 'Infrastructure servic...","47,79,62,39",339900000,339900000,http://www.worldbank.org/projects/P075941/nels...,NaN
99,{'$oid': '52b213b38594d8a2be17c7e3'},2013,June,2013-06-28T00:00:00Z,GOVERNMENT OF MALI,NaN,Africa!$!3A,3A,Africa,Africa,...,IBRD,Active,Y,"{'Percent': 25, 'Name': 'Regional integration'}","[{'code': '47', 'name': 'Regional integration'...","78,27,48,47",60000000,60000000,http://www.worldbank.org/projects/P145160/addi...,NaN
167,{'$oid': '52b213b38594d8a2be17c827'},2013,May,2013-05-30T00:00:00Z,MINISTRIES OF TELECOM AND ICT,2018-11-30T00:00:00Z,Africa!$!3A,3A,Africa,Africa,...,IBRD,Active,N,"{'Percent': 25, 'Name': 'Regional integration'}","[{'code': '47', 'name': 'Regional integration'...","48,40,39,47",60000000,60000000,http://www.worldbank.org/projects/P123093/west...,NaN
184,{'$oid': '52b213b38594d8a2be17c838'},2013,May,2013-05-21T00:00:00Z,TANZANIA,2018-12-31T00:00:00Z,Africa!$!3A,3A,Africa,Africa,...,IBRD,Active,N,"{'Percent': 23, 'Name': 'Regional integration'}","[{'code': '47', 'name': 'Regional integration'...","88,74,49,47",213000000,213000000,http://www.worldbank.org/projects/P120370/sout...,NaN
287,{'$oid': '52b213b38594d8a2be17c89f'},2013,March,2013-03-14T00:00:00Z,"MALAWI, MOZAMBIQUE, ZAMBIA",2020-01-31T00:00:00Z,Africa!$!3A,3A,Africa,Africa,...,IBRD,Active,N,"{'Percent': 80, 'Name': 'Rural services and in...","[{'code': '78', 'name': 'Rural services and in...","47,48,78",90000000,90000000,http://www.worldbank.org/projects/P094183/agri...,NaN
353,{'$oid': '52b213b38594d8a2be17c8e1'},2013,January,2013-01-01T00:00:00Z,NILE BASIN INITIATIVE,2015-12-31T00:00:00Z,Africa!$!3A,3A,Africa,Africa,...,IBRD,Active,N,"{'Percent': 74, 'Name': 'Water resource manage...","[{'code': '85', 'name': 'Water resource manage...","82,57,85",0,15300000,http://www.worldbank.org/projects/P130694/nile...,NaN
449,{'$oid': '52b213b38594d8a2be17c941'},2013,October,2012-10-02T00:00:00Z,GOVERNMENT OF NIGER,2020-04-01T00:00:00Z,Africa!$!3A,3A,Africa,Africa,...,IBRD,Active,N,"{'Percent': 10, 'Name': 'Municipal governance ...","[{'code': '73', 'name': 'Municipal governance ...","47,78,85,73",203000000,203000000,http://www.worldbank.org/projects/P130174/firs...,NaN

The Top 10 Countries with the most projects are:

China, Indonesia, Vietnam, India, Yemen, Nepal, Bangladesh, Morocco, Mozambique and Tanzania(not Africa).

For this project: Since Africa is not a country, we need to see if we can get more detail. 
Looking at rows with Africa yields two more entries for Tanzania, bumping it to number 10 on the list.

## Questions 2 & 3
Finding the Top 10 Project Themes and replacing any missing values in the Name column.

To answer this question we will load the json file as text instead of the previous method.

In [119]:
# Load the json file as text.
df = json.load((open('world_bank_projects.json')))

# Normalize the data in the major project theme column for easier analysis.
easy = json_normalize(df, 'mjtheme_namecode')

# Look at a some rows.
easy.head()

  code                                   name
0    8                      Human development
1   11
2    1                    Economic management
3    6  Social protection and risk management
4    5                  Trade and integration

To answer this question we need a complete dataset.
So first we have to fill any blanks with NA.
Then we need to replace the NAs with values from the row above.
Finally, we can count and sort to answer find the 10 ten themes.

In [126]:
# Fill missing cells with NaNs.
easy[easy['name'] == ''] = np.nan

In [131]:
# Replace the NAs by forward filling.
easy = easy.fillna(method='ffill')

In [135]:
# Chain methods to 
final = easy.groupby('name').count().sort_values('code',ascending =False)
final.head(10)

                                              code
name
Environment and natural resources management   248
Human development                              223
Rural development                              216
Public sector governance                       203
Social protection and risk management          168
Financial and private sector development       145
Social dev/gender/inclusion                    127
Trade and integration                           73
Urban development                               49
Economic management                             35

The Top 10 project themes in descending order are shown in the table above.